import random

import problems_quiz_errors as p
import functions_quiz_errors as f
# import data_quiz_errors as d

if __name__ == '__main__':
    problem_list = [
            p.problem_one,
            # p.problem_two,
            # p.problem_three,
            # p.problem_four,
            # p.problem_five, 
            # p.problem_six, 
            # p.problem_seven,
            # p.problem_eight, 
            # p.problem_nine,
            # p.problem_ten,
            # p.problem_eleven,
            # p.problem_twelve, 
            # p.problem_thirteen, 
            # p.problem_fourteen,
            # p.problem_fifteen, 
            # p.problem_sixteen,
            # p.problem_seventeen,
            # p.problem_eighteen,
            # p.problem_nineteen,
            # p.problem_twenty,
            # p.problem_twenty_one,
            # p.problem_twenty_two,
            # p.problem_twenty_three,
            # p.problem_twenty_four,
            # p.problem_twenty_five,
            # p.problem_twenty_six,
            # p.problem_twenty_seven,
            # p.problem_twenty_eight,
            # p.problem_twenty_nine,
            # p.problem_thirty,        
            # p.problem_thirty_one,        
            # p.problem_thirty_two,        
            # p.problem_thirty_three,        
            # p.problem_thirty_four,        
            # p.problem_thirty_five,        
            # p.problem_thirty_six,        
            # p.problem_thirty_seven,        
            # p.problem_thirty_eight,        
            # p.problem_thirty_nine,        
            # p.problem_forty,        
            # p.problem_forty_one,        
            # p.problem_forty_two,        
            # p.problem_forty_three,        
            # p.problem_forty_four,        
            # p.problem_forty_five,        
            # p.problem_forty_six,        
            # p.problem_forty_seven,        
            # p.problem_forty_eight,        
            # p.problem_forty_nine,        
            # p.problem_fifty,        
            # p.problem_fifty_one,        
            # p.problem_fifty_two,        
            # p.problem_fifty_three,        
            # p.problem_fifty_four,        
            # p.problem_fifty_five,        
            # p.problem_fifty_six,        
            # p.problem_fifty_seven,        
            # p.problem_fifty_eight,        
            # p.problem_fifty_nine,        
            # p.problem_sixty,        
            # p.problem_sixty_one,        
            # p.problem_sixty_two,        
            # p.problem_sixty_three,        
            # p.problem_sixty_four,        
            # p.problem_sixty_five,        
            # p.problem_sixty_six,        
            # p.problem_sixty_seven,        
            # p.problem_sixty_eight,        
            # p.problem_sixty_nine,        
            # p.problem_seventy,        
            # p.problem_seventy_one,        
            # p.problem_seventy_two,        
            # p.problem_seventy_three,        
            # p.problem_seventy_four,        
            # p.problem_seventy_five,        
            # p.problem_seventy_six,        
            # p.problem_seventy_seven,        
            # p.problem_seventy_eight,        
            # p.problem_seventy_nine,        
            # p.problem_eighty,        
            # p.problem_eighty_one,        
            # p.problem_eighty_two,        
            # p.problem_eighty_three,        
            # p.problem_eighty_four,        
            # p.problem_eighty_five,        
            # p.problem_eighty_six,        
            # p.problem_eighty_seven,        
            # p.problem_eighty_eight,        
            # p.problem_eighty_nine,        
            # p.problem_ninety,        
            # p.problem_ninety_one,        
            # p.problem_ninety_two,        
            # p.problem_ninety_three,        
            # p.problem_ninety_four,        
            # p.problem_ninety_five,        
            # p.problem_ninety_six,        
            # p.problem_ninety_seven,        
            # p.problem_ninety_eight,        
            # p.problem_ninety_nine,        
            # p.problem_one_hundred,        
            # p.problem_hundred_one,        
            # p.problem_hundred_two,        
            # p.problem_hundred_three,        
            # p.problem_hundred_four,        
            # p.problem_hundred_five,        
            # p.problem_hundred_six,        
            # p.problem_hundred_seven,        
            # p.problem_hundred_eight,        
            # p.problem_hundred_nine,        
            # p.problem_hundred_ten,        
            # p.problem_hundred_eleven,        
            # p.problem_hundred_twelve,        
            # p.problem_hundred_thirteen,        
            # p.problem_hundred_fourteen,        
            # p.problem_hundred_fifteen,        
            # p.problem_hundred_sixteen,        
            # p.problem_hundred_seventeen,        
            # p.problem_hundred_eighteen,        
            # p.problem_hundred_nineteen,        
            # p.problem_hundred_twenty,        
            # p.problem_hundred_twenty_one,        
            # p.problem_hundred_twenty_two,        
            # p.problem_hundred_twenty_three,        
            # p.problem_hundred_twenty_four,        
            # p.problem_hundred_twenty_five,        
            # p.problem_hundred_twenty_six,        
            # p.problem_hundred_twenty_seven,        
            # p.problem_hundred_twenty_eight,        
            # p.problem_hundred_twenty_nine,        
            # p.problem_hundred_thirty,        
            # p.problem_hundred_thirty_one,        
            # p.problem_hundred_thirty_two,        
            # p.problem_hundred_thirty_three,        
            # p.problem_hundred_thirty_four,        
            # p.problem_hundred_thirty_five,        
            # p.problem_hundred_thirty_six,        
            # p.problem_hundred_thirty_seven,        
            # p.problem_hundred_thirty_eight,        
            # p.problem_hundred_thirty_nine,        
            # p.problem_hundred_forty,        
            # p.problem_hundred_forty_one,        
            # p.problem_hundred_forty_two,        
            # p.problem_hundred_forty_three,        
            # p.problem_hundred_forty_four,        
            p.problem_hundred_forty_five,        
            p.problem_hundred_forty_six,        
            ]
    random_problem_list = random.sample(problem_list, k=len(problem_list)) # k = problem_number
    question_counter = f.counter(len(problem_list))
    f.display_problem(random_problem_list[0],question_counter, len(problem_list))
    i = 1
    quit = False
    while not quit and i < len(problem_list):  # i < problem_number
        choice =f.next_question(random_problem_list[i], f.continue_choice, question_counter, len(problem_list))
        i += 1
        quit = not choice

